//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Inputs/KeyboardInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @KeyboardInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @KeyboardInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""KeyboardInputs"",
    ""maps"": [
        {
            ""name"": ""Keyboard"",
            ""id"": ""f5879437-3d98-4984-a5d0-19c8d4670960"",
            ""actions"": [
                {
                    ""name"": ""Any_Press"",
                    ""type"": ""Value"",
                    ""id"": ""7f7986ab-5f02-468b-ac67-ed46373c1bdb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""09ed63f9-fb8f-4b88-964f-ad31e8fe8bed"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Any_Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Keyboard
        m_Keyboard = asset.FindActionMap("Keyboard", throwIfNotFound: true);
        m_Keyboard_Any_Press = m_Keyboard.FindAction("Any_Press", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Keyboard
    private readonly InputActionMap m_Keyboard;
    private IKeyboardActions m_KeyboardActionsCallbackInterface;
    private readonly InputAction m_Keyboard_Any_Press;
    public struct KeyboardActions
    {
        private @KeyboardInputs m_Wrapper;
        public KeyboardActions(@KeyboardInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Any_Press => m_Wrapper.m_Keyboard_Any_Press;
        public InputActionMap Get() { return m_Wrapper.m_Keyboard; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KeyboardActions set) { return set.Get(); }
        public void SetCallbacks(IKeyboardActions instance)
        {
            if (m_Wrapper.m_KeyboardActionsCallbackInterface != null)
            {
                @Any_Press.started -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAny_Press;
                @Any_Press.performed -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAny_Press;
                @Any_Press.canceled -= m_Wrapper.m_KeyboardActionsCallbackInterface.OnAny_Press;
            }
            m_Wrapper.m_KeyboardActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Any_Press.started += instance.OnAny_Press;
                @Any_Press.performed += instance.OnAny_Press;
                @Any_Press.canceled += instance.OnAny_Press;
            }
        }
    }
    public KeyboardActions @Keyboard => new KeyboardActions(this);
    public interface IKeyboardActions
    {
        void OnAny_Press(InputAction.CallbackContext context);
    }
}
